services:
  dbase-service:
    image: postgres:13.8
    container_name: dbase-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROD_POSTGRES_DB_NAME}
      POSTGRES_HOST: ${PROD_POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - "${PROD_POSTGRES_DB_PORT}:5432"
    volumes:
      - ./DockerVolumes/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PROD_POSTGRES_DB_NAME} -U ${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      timeout: 5s